sudo: false

addons:
  apt:
    packages:
    - python-numpy 
    - python-scipy 
    
language: python

python: 2.7

virtualenv:
    system_site_packages: true

install:
  
  # install pyelectro
  - pip install git+https://github.com/NeuralEnsemble/pyelectro.git
  
  # install inspyred
  - pip install inspyred
  
  # install neurotune
  - python setup.py install

# command to run tests
script:  
  - cd examples/example_4
  - python SineWavePointOptimizer.py -nogui  # run one of the examples supressing plots etc.
  

