sudo: false

addons:
  apt:
    packages:
    - python-numpy 
    - python-scipy 
    # Quick fix, requires matrix for addons...
    - python3-numpy 
    - python3-scipy 
    
language: python

python: 
  - "2.7"
  - "3.2"

virtualenv:
    system_site_packages: true

install:
  
  # install pyelectro
  - pip install git+https://github.com/NeuralEnsemble/pyelectro.git
  
  # install inspyred
  - pip install inspyred
  
  # Install OMV to facilitate installation of Neuron
  - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

  # install neurotune
  - python setup.py install

# command to run tests
script:  
  - if [[ $TRAVIS_PYTHON_VERSION -ne "2.7" ]]; then exit 0 ; fi  # OMV only works in Python 2 so far...
  
  # Need to pre install PyNEURON for testing models
  - omv install PyNEURON
  - export NEURON_HOME=/home/travis/neuron/nrn/x86_64/
  - export PATH=$PATH:$NEURON_HOME/bin

  - ./test.sh
  

