
dist: xenial
sudo: false

addons:
  apt:
    packages:
    - python-numpy 
    
language: python

python: 
  - "2.7"
  - "3.5"
  - "3.7"  


install:
  
  # install scipy
  - pip install scipy>=1.3.3  # install via pip here to ensure recent version
  
  # install pyelectro
  - pip install git+https://github.com/NeuralEnsemble/pyelectro.git
  
  # install inspyred
  - pip install inspyred
  
  
  # Install OMV to facilitate installation of Neuron
  - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

  # install neurotune
  - python setup.py install

# command to run tests
script:  
  #- if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then exit 0 ; fi  # Only run OMV in Python 2...
  
  # Need to pre install PyNEURON for testing models
  - omv install PyNEURON
  - export NEURON_HOME=/home/travis/neuron/nrn/x86_64/
  - export PATH=$PATH:$NEURON_HOME/bin
  - env
  - omv list -V 

  - ./test.sh
  

