language: python

python:
  - "2.7"
  #- "3.2"

install:
  # Install conda to facilitate installation of numpy, scipy etc.
  - sudo pip install conda
  - sudo conda init
  
  # install dependencies
  - deps='pip numpy scipy'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  
  # install pyelectro
  - pip install git+https://github.com/pgleeson/pyelectro.git
  
  # install inspyred
  - pip install inspyred
  
  # install neurotune
  - python setup.py install

# command to run tests
script:  
  - cd examples/example_4
  - python SineWavePointOptimizer.py -nogui  # run one of the examples supressing plots etc.
  

