sudo: false

addons:
  apt:
    packages:
    - python-numpy 
    - python-scipy 
    # Quick fix, requires matrix for addons...
    - python3-numpy 
    - python3-scipy 
    
language: python

python: 
  - "2.7"
  - "3.2"

virtualenv:
    system_site_packages: true

install:
  
  # install pyelectro
  - pip install git+https://github.com/NeuralEnsemble/pyelectro.git
  
  # install inspyred
  - pip install inspyred
  
  # install neurotune
  - python setup.py install

# command to run tests
script:  
  - cd examples/example_4
  - python SineWavePointOptimizer.py -nogui  # run one of the examples supressing plots etc.
  

